### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by hkloudou** [TGIF-iMatrix/MXFlutter#46]
这个库引入了大量的第三方包，可能会不可避免的导致某些包升级的时候引发bug
XCODE：11.5
FLUTTER：1.22.6
git 引入的是v0.8.0-beta
各种测试  要么提示找不到FMDB.h
要么提示Error: Method not found: 'TransitionBuilderPage'.
反正，就半小时了，没有跑起来。
大家有没有测试通过的环境版本写到README里去啊

**Comment by mxflutter** [comment]
README有写，v0.8.0是对应 Flutter 1.20.3版本，后面我们做个表格。

**Comment by hkloudou** [comment]
@mxflutter 您用的XCODE是哪个版本呢

Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/MXJSFlutterEngine.m:15:
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.h:15:39: warning: this function declaration is not a
    prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    In file included from
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/MXJSFlutterApp.m:15:
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.h:15:39: warning: this function declaration is not a
    prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    In file included from
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/MXJSEngine.m:16:
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.h:15:39: warning: this function declaration is not a
    prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    In file included from
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.m:11:
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-e2b41f02e668776f9be172a6a703874255217549/mxflut
    ter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.h:15:39: warning: this function declaration is not a
    prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:40:81: error: use of undeclared identifier 'PHAccessLevelAddOnly'
            [PHPhotoLibrary
            requestAuthorizationForAccessLevel:(addOnlyAccessLevel)?PHAccessLevelAddOnly:PHAccessLevelReadWrite
            handler:^(PHAuthorizationStatus authorizationStatus) {
                                                                                    ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:40:102: error: use of undeclared identifier 'PHAccessLevelReadWrite'
            [PHPhotoLibrary
            requestAuthorizationForAccessLevel:(addOnlyAccessLevel)?PHAccessLevelAddOnly:PHAccessLevelReadWrite
            handler:^(PHAuthorizationStatus authorizationStatus) {
                                                                                                         ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:53:89: error: use of undeclared identifier 'PHAccessLevelAddOnly'
            status = [PHPhotoLibrary
            authorizationStatusForAccessLevel:(addOnlyAccessLevel)?PHAccessLevelAddOnly:PHAccessLevelReadWrite];
                                                                                            ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:53:110: error: use of undeclared identifier 'PHAccessLevelReadWrite'
            status = [PHPhotoLibrary
            authorizationStatusForAccessLevel:(addOnlyAccessLevel)?PHAccessLevelAddOnly:PHAccessLevelReadWrite];
                                                                                                                 ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:71:14: error: use of undeclared identifier
    'PHAuthorizationStatusLimited'; did you mean 'PHAuthorizationStatusDenied'?
            case PHAuthorizationStatusLimited:
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 PHAuthorizationStatusDenied
    In module 'Photos' imported from
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.h:11:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator1
    3.5.sdk/System/Library/Frameworks/Photos.framework/Headers/PHPhotoLibrary.h:22:5: note:
    'PHAuthorizationStatusDenied' declared here
        PHAuthorizationStatusDenied,            // User has explicitly denied this application access to photos
        data.
        ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:71:14: error: duplicate case value 'PHAuthorizationStatusDenied'
            case PHAuthorizationStatusLimited:
                 ^
    /Users/undefined/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-5.1.0+2/ios/Class
    es/strategies/PhotoPermissionStrategy.m:67:14: note: previous case defined here
            case PHAuthorizationStatusDenied:
                 ^
    6 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

这个是完整的报错

**Comment by hkloudou** [comment]
上一个 问题确认是 permission_handler组件引起的，在XCODE11下 要使用：permission_handler: 5.0.0+hotfix.10，才可以解决问题。或者升级到最新版XCODE

在mac64为调试模拟器调试遇到新的提示：
Xcode's output:
↳
    1 warning generated.
    1 warning generated.
    1 warning generated.
    In file included from
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-4c6e6a06e09080c737fcde38a4a2384085d1700c/mxflutter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.m:11:
    /Users/undefined/development/flutter/.pub-cache/git/mxflutter-4c6e6a06e09080c737fcde38a4a2384085d1700c/mxflutter/ios/Classes/MXFlutterOCFramework/Common/MXCommon.h:15:39:
    warning: this function declaration is not a prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    While building module 'mxflutter' imported from /Users/undefined/project/wallet/app/abcBank/ios/Runner/GeneratedPluginRegistrant.m:8:
    In file included from <module-includes>:1:
    In file included from /Users/undefined/project/wallet/app/abcBank/ios/Pods/Headers/Public/mxflutter/mxflutter-umbrella.h:13:
    /Users/undefined/project/wallet/app/abcBank/ios/Pods/Headers/Public/mxflutter/MXCommon.h:15:39: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    NSString* mxflutterJSBundleDefaultPath();
                                          ^
                                           void
    1 warning generated.
    1 warning generated.
    Undefined symbols for architecture x86_64:
      "___cxa_begin_catch", referenced from:
          ___clang_call_terminate in libmxflutter.a(MXFFICallbackManager.o)
      "std::terminate()", referenced from:
          ___clang_call_terminate in libmxflutter.a(MXFFICallbackManager.o)
      "___gxx_personality_v0", referenced from:
          _NativeCallFlutterFunctionSync in libmxflutter.a(MXFFICallbackManager.o)
          PendingCall::PendingCall(void**, unsigned long*) in libmxflutter.a(MXFFICallbackManager.o)
          PendingCall::~PendingCall() in libmxflutter.a(MXFFICallbackManager.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

我继续测试真机模式。。。

**Comment by hkloudou** [comment]
真机也不通过，就有点方。。。

ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by hkloudou** [comment]
加上-v后的完整报错，，，有点郁闷，我去升级下系统和XCODE再看行不行。。。

/Users/undefined/Library/Developer/Xcode/DerivedData/Runner-dgovbibzsifnvmfvdwmhsvkemmsh/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-
                   normal/x86_64/Runner_dependency_info.dat -o /Users/undefined/project/wallet/app/abcBank/build/ios/Debug-iphonesimulator/Runner.app/Runner
               Undefined symbols for architecture x86_64:
                 "___cxa_begin_catch", referenced from:
                     ___clang_call_terminate in libmxflutter.a(MXFFICallbackManager.o)
                 "std::terminate()", referenced from:
                     ___clang_call_terminate in libmxflutter.a(MXFFICallbackManager.o)
                 "___gxx_personality_v0", referenced from:
                     _NativeCallFlutterFunctionSync in libmxflutter.a(MXFFICallbackManager.o)
                     PendingCall::PendingCall(void**, unsigned long*) in libmxflutter.a(MXFFICallbackManager.o)
                     PendingCall::~PendingCall() in libmxflutter.a(MXFFICallbackManager.o)
               ld: symbol(s) not found for architecture x86_64
               clang: error: linker command failed with exit code 1 (use -v to see invocation)
           
           
[  +77 ms] Could not build the application for the simulator.
[   +2 ms] Error launching application on x.
[   +3 ms] "flutter run" took 15,695ms.
[   +6 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:741:33)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #6      _rootRun (dart:async/zone.dart:1190:13)
           #7      _CustomZone.run (dart:async/zone.dart:1093:19)
           #8      _runZoned (dart:async/zone.dart:1630:10)
           #9      runZoned (dart:async/zone.dart:1550:10)
           #10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:730:20)
           #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:332:21)
           #14     _rootRunUnary (dart:async/zone.dart:1198:47)
           #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #21     _rootRun (dart:async/zone.dart:1190:13)
           #22     _CustomZone.run (dart:async/zone.dart:1093:19)
           #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[   +1 ms] ensureAnalyticsSent: 0ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by hkloudou** [comment]
@mxflutter 我找到原因了，很郁闷。
我在初始化flutter的时候 习惯用 加上参数 -i objc -a java，这样可以让打包出来的ios尺寸大大减小，因为用objc，而不是swift。
而这个包，在objc模式下，竟然会报错libmxflutter出错。强烈建议加上非swift模式下的支持，或者，我有兴趣参与修改。。。
